client/html/package-lock.json
client/html/package.json
client/react/package-lock.json
client/react/package.json
server/java/build.gradle
server/node/package-lock.json
server/node/package.json

A minor annoyance.
Once this is merged, my intention is to re-tag `v0.1.0` and re-release.
Signed-off-by: Johan Fylling <johan.dev@fylling.se>

Bumping verisons to 0.1.0

---

client/html/package.json
client/html/public/admin.html
server/node/package.json
server/node/src/api.js
server/node/src/server.js

no code changes, mostly formatting

node and js tweaks

---

client/html/package-lock.json
client/html/public/admin.html
client/html/public/new_ticket.html
client/html/public/scripts/login.js
client/html/public/stylesheets/style.css
client/html/public/ticket.html
client/html/public/tickets.html
client/react/public/index.html
client/react/src/components/App.jsx
client/react/src/components/Nav.jsx
client/react/src/style.css
client/react/src/useAccounts.js
server/node/package-lock.json

- add tenant title
- simplify user select with tenant groups

update html and react client to new header

---

client/html/package.json
client/react/package.json
server/java/build.gradle
server/node/package.json

Signed-off-by: Johan Fylling <johan.dev@fylling.se>

Bumping versions to 0.2.0

---

server/node/package-lock.json
server/node/package.json
server/node/src/authz.js

https://www.npmjs.com/package/@styra/opa

server/node: use @styra/opa from NPM

---

.github/workflows/pull-request.yaml
server/java/build.gradle
server/java/src/main/java/com/styra/tickethub/Storage.java
server/java/src/main/java/com/styra/tickethub/TicketHub.java

* Fixed a few inconsistencies between the Java server and the integration tests, enabled Java integration tests.
* Added new GHA triggers to run all integration tests on push and at midnight UTC.
* Changed Java server to use the `+` version of opa-java, which will cause Gradle to always download the latest release. This will make the integration tests double as regression tests for opa-java.

java integration test working, add cron trigger

---

client/react/src/AuthnContext.js
client/react/src/components/App.jsx
client/react/src/components/Nav.jsx
client/react/src/components/NewTicket.jsx
client/react/src/components/Ticket.jsx
client/react/src/components/Tickets.jsx
client/react/src/useAccounts.js
server/node/src/api.js
server/node/src/server.js
tests/api/basic.hurl

server/node: check authorization header first, then try cookie fallback
tests/api: send both a header and a cookie
client/react: send headers, use AuthnContext for value propagation

introduce header auth

---

.github/workflows/pull-request.yaml
client/react/src/components/Nav.jsx
client/react/src/useAccounts.js
tests/e2e/.gitignore
tests/e2e/package-lock.json
tests/e2e/package.json
tests/e2e/playwright.config.ts
tests/e2e/tests/tickets.spec.ts

tests/e2e: add simple playwright suite

---

client/react/packages/opa-react/src/authz.tsx
client/react/packages/opa-react/src/index.ts
client/react/packages/opa-react/tests/authz.test.tsx
client/react/packages/opa-react/tests/setup.ts
client/react/src/components/Ticket.jsx
client/react/src/components/Tickets.jsx

opa-react: simplify <Authz> helper

---

client/react/package-lock.json
client/react/package.json

Dependabot didn't pick this up because of the previous constraint.

client/react: bump @styra/opa

---

client/react/package-lock.json
client/react/package.json
client/react/src/components/App.jsx
client/react/src/components/Ticket.jsx
client/react/src/components/Tickets.jsx

1. bump @strya/opa-react to 0.5.0, rename props accordingly
2. fix app initialization logic, cleanup stray `)`
3. put more buttons on the ticket list so we've got something to batch later

client/react: bump @styra/opa-react to 0.5.0

---

server/java/build.gradle
server/springboot/build.gradle

This is because I'd like to see the dependabot PRs and the corresponding checks.

server/springboot: pin versions of opa[-springboot]

---

server/node/prisma/schema.prisma

https://www.prisma.io/blog/prisma-orm-now-lets-you-choose-the-best-join-strategy-preview

schema.prisma: add previewFeature 'relationJoins'

---

server/csharp/TicketHub/Controllers/TicketController.cs

This PR wraps up some ugly-but-effective bits to allow pulling UCAST straight from the new `/v1/compile` API in EOPA.
The result is that we're using a *much* more intelligible data filtering policy now, without really changing most of the LINQ machinery in the C# TicketHub server.

csharp: Refactor conditions logic to use /v1/compile from EOPA.

---

enterprise-opa.Dockerfile
policies/tickets.rego

1. latest now has the Compile API changes (no need for :edge)
2. remove previous approach of conditions-built-via-rego
3. remove redundant rules for reason_user

policies, docker: leftover updates

---

server/csharp/TicketHub/Database/Customer.cs
server/csharp/TicketHub/Database/PostgresContext.cs
server/csharp/TicketHub/Database/Tenant.cs
server/csharp/TicketHub/Database/User.cs
server/csharp/database/init.sql
server/node/database/init.sql

This PR adds PII fields to the database models, like phone numbers and emails, for customers and support users. It also adds the concept of a "region" for the tenant, which could be used to emulate data protection regulatory policies down the road.

server/csharp: Upgrade DB + ORM models for maskable fields.

---

server/aspnetcore/TicketHub/Database/Customer.cs
server/aspnetcore/TicketHub/Database/PostgresContext.cs
server/aspnetcore/TicketHub/Database/Tenant.cs
server/aspnetcore/TicketHub/Database/Ticket.cs
server/aspnetcore/TicketHub/Database/User.cs
server/aspnetcore/database/init.sql
server/csharp/database/init.sql

This PR adds PII fields to the database models, like phone numbers and emails, for customers and support users. It also adds the concept of a "region" for the tenant, which could be used to emulate data protection regulatory policies down the road.
This is an intentional, and almost exact duplicate of the work on #566.

server/aspnetcore: Upgrade DB + ORM models for maskable fields.

---

.github/workflows/pull-request.yaml
Makefile
policies/filters.rego
policies/filters_test.rego

This adds exemplary filter tests and low-level tests for our data filtering logic: https://github.com/StyraInc/styra-demo-tickethub/pull/593/files#diff-3d91692f79ee2d62bfff1f5bd65c40f5cbe7b8515efffbcbeb346d8bd97fc7ee

policies: unit test data filter policies

---

client/react/package-lock.json
client/react/packages/opa-wasm/package-lock.json
client/react/packages/opa-wasm/package.json

client/react: bump esbuild

---

.github/dependabot.yml

To avoid these PRs that never compile: https://github.com/StyraInc/styra-demo-tickethub/pull/598

dependabot: ignore jetty+jersey

---

Makefile
enterprise-opa.Dockerfile
server/node/package-lock.json
server/node/package.json
server/node/src/api.js
server/node/src/authz.js

server/node: adapt to getFilter() SDK method, remove wrapper
