- .github/workflows/pull-request.yaml
- Makefile
- docker-compose.yaml
- server/csharp/.dockerignore
- server/csharp/.env
- server/csharp/.gitignore
- server/csharp/Dockerfile
- server/csharp/LICENSE
- server/csharp/Makefile
- server/csharp/README.md
- server/csharp/TicketHub.sln
- server/csharp/TicketHub/Authorization/OpaAuthorizationAttribute.cs
- server/csharp/TicketHub/Authorization/OpaAuthzService.cs
- server/csharp/TicketHub/Controllers/TicketController.cs
- server/csharp/TicketHub/CookieMiddleware.cs
- server/csharp/TicketHub/Database/Customer.cs
- server/csharp/TicketHub/Database/PostgresContext.cs
- server/csharp/TicketHub/Database/Tenant.cs
- server/csharp/TicketHub/Database/Ticket.cs
- server/csharp/TicketHub/Program.cs
- server/csharp/TicketHub/TicketHub.csproj
- server/csharp/TicketHub/appsettings.Development.json
- server/csharp/TicketHub/appsettings.json
- server/csharp/database/init.sql
This PR contains a C# TicketHub server implementation (in ASP.NET Core, specifically), along with the necessary infrastructure to get it up and running.
If you're using the top-level `docker-compose.yaml`, try the somewhat verbose/ugly invocation:
VARIANT=csharp docker compose --profile csharp build && VARIANT=csharp docker compose --profile csharp --profile tools up
This will build the docker image for the C# TicketHub server, and then launch the top-level `docker-compose` under the `csharp` profile (selecting "always on" and "csharp"-specific services).
You can shut down the pile of services with the following invocation:
VARIANT=csharp docker compose --profile csharp --profile tools down
In the `server/csharp` directory, run `make run`, and then fire requests at the appropriate …
> C# TicketHub server implementation

- server/csharp/TicketHub/Controllers/TicketController.cs
- server/csharp/TicketHub/Database/Ticket.cs
This PR fixes an issue where the UI would not display timestamps, or appear to visibly update them during ticket resolve/unresolve UI interactions, when using the `csharp` server profile.
The cause was the C# server's EF Core model expecting (and serializing) the field as `lastUpdated` instead of `last_updated`. By adding a few model annotations + UTC conversion logic in the controller, things seem to be back in working order.
<details>
<summary><b>curl /tickets before fix</b></summary>
```bash
$ curl --header 'Content-Type: application/json' --cookie 'user=acmecorp / bob' 'http://localhost:4000/api/tickets'
{"tickets":[{"id":11,"description":"Gibberish gibberish","lastUpdated":"2024-04-30T21:26:35.816112","resolved":true,"customer":"Globex","tenant":"acmecorp"},{"id":2,"description":"Flam …
```
> server/csharp: Fix issues around `last_updated` field.

- .github/dependabot.yml
This PR updates our Dependabot config to auto-update NuGet dependencies for the C# server.
**Note**: I'm not certain that Dependabot will recurse correctly down to where the `.csproj` file is (`/server/csharp/TicketHub`), so there may be a follow-up PR after this one, depending on whether or not we start seeing version bump PRs in the next day or two.
> ci: Add Dependabot config for updating the C# server.

- .github/workflows/pull-request.yaml
- README.md
- client/react/Dockerfile
1. Build wasm module in CI run for client/{html,react}.
2. mention new make call in top-level README. **Note**: I have not invested time in updating the docker container for that... we'd need to use the OPA from the OPA container to build something that's used in the client/react container... But we can revisit if we feel strongly about this.
> client/react: copy packages/ in Dockerfile

- client/react/Dockerfile
- client/react/caddy/Caddyfile
This is to workaround this problem:
```
> styra-tickethub-react@0.3.0 start
> react-scripts start
Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
- options.allowedHosts[0] should be a non-empty string.
```
Relying on the dev server for our "normal deployment" is icky to begin with, so this changes it: we'll now build the react app into `build/`, and serve that, as it should be, from a stupid HTTP server.
> client/react: use prod build + caddy

- client/react/.env
- client/react/README.md
This way, tickethub serves as a nice extra integration test. It would do that for opa-wasm, too, but since `@strya/opa` is a released, promoted packaged, we should test that first.
> client/react: use @styra/opa by default

- .github/workflows/pull-request.yaml
- client/react/src/components/App.jsx
- docker-compose.yaml
- enterprise-opa.Dockerfile
- tests/e2e/package-lock.json
- tests/e2e/package.json
- tests/e2e/tests/tickets.spec.ts
There is a new button 😅 It's slightly ugly but the best I could do 👇 
Its initial value is taken from `?batch=true`, so if you want to enable batch requests **from the start**, you'll go to http://localhost:3000/?batch=true. This is also what playwright does in the extra test suite.
Note that to have the backend ready, you'll need to start EOPA instead of OPA. This can be done by setting `OPA_DOCKERFILE=enterprise-opa.Dockerfile`, while having `EOPA_LICENSE_KEY` set to a license key.
> client/react: enable batching by env var, do it in tests, too

- server/csharp/TicketHub/Authorization/OpaAuthorizationAttribute.cs
- server/csharp/TicketHub/Authorization/OpaAuthzService.cs
- server/csharp/TicketHub/Controllers/TicketController.cs
- server/csharp/TicketHub/Program.cs
This commit includes 2x changes:
- We now properly tie in the `OpaClient`'s logging into the ASP.NET logging system. (Via dependency injection.)
- We now implement the authz controls on the endpoints with an `AuthorizationFilter` attribute. This is a slightly better fit overall, and allows rejecting bad requests earlier in the controller filter path.
The original implementation was an `ActionFilterAttribute`, which was more powerful than we needed, and runs later in the authorization process.
The original ActionFilterAttribute implementation has been left in, to serve as a basic reference. I'm open to either leaving it alone, or removing it entirely.
- https://learn.microsoft.com/en-us/aspnet/mvc/overview/older-versions-1/controllers-and-routing/understanding-action-filters-cs#the-differen …
> server/csharp: Update to use logging + authz attribute.

- server/springboot/src/main/java/com/styra/tickethub_springboot/dao/model/CustomAuthentication.java
- server/springboot/src/main/java/com/styra/tickethub_springboot/dao/model/CustomAuthenticationFilter.java
- server/springboot/src/main/java/com/styra/tickethub_springboot/dao/model/SecurityConfig.java
I thought I pulled this in with my reason field support for the HTML client, but apparently it got lost during repo surgery. This PR pulls in those changes.
Basically, this adds a custom spring authN implementation which uses the TicketHub's custom authz header format, meaning Spring will now think TicketHub users are really Authenticated. This has some nice properties on the Spring side, and should not impact the existing API functionality in any way.
> adopt Spring authN for TicketHub backend

- .github/workflows/pull-request.yaml
- Makefile
- README.md
- docker-compose.yaml
- policies/aspnetcore.rego
- server/aspnetcore/.dockerignore
- server/aspnetcore/.gitignore
- server/aspnetcore/Dockerfile
- server/aspnetcore/LICENSE
- server/aspnetcore/Makefile
- server/aspnetcore/README.md
- server/aspnetcore/TicketHub.sln
- server/aspnetcore/TicketHub/Controllers/TicketController.cs
- server/aspnetcore/TicketHub/CookieMiddleware.cs
- server/aspnetcore/TicketHub/Database/Customer.cs
- server/aspnetcore/TicketHub/Database/PostgresContext.cs
- server/aspnetcore/TicketHub/Database/Tenant.cs
- server/aspnetcore/TicketHub/Database/Ticket.cs
- server/aspnetcore/TicketHub/Program.cs
- server/aspnetcore/TicketHub/TicketHub.csproj
- server/aspnetcore/TicketHub/appsettings.Development.json
- server/aspnetcore/TicketHub/appsettings.json
- server/aspnetcore/database/init.sql
This PR adds a new C# server implementation, one that leverages the [`Styra.Opa.AspNetCore`](https://github.com/StyraInc/opa-aspnetcore) middleware library. It also wires in the new server implementation into existing CI tests.
*Note: I owe a debt of gratitude to @charlesdaniels for putting together the Spring Boot policy, from which I derived 90%+ of the policy for the ASP.NET Core SDK server.*
The main changes for the *TicketHub server* from the original C# SDK are:
- Removed the custom `Authorization` attribute implementations for the controller.
- Rewrote the custom cookie authentication system to integrate as an ASP.NET Authentication method.
- This allows us to wire it into the app configuration, and later enable it with `app.UseAuthorization()`!
The main changes for the *policy* …
> server/aspnetcore: Add ASP.NET Core SDK server.

- README.md
- policies/tickets.rego
- server/java/src/main/java/com/styra/tickethub/ForbiddenExceptionWithReason.java
- server/java/src/main/java/com/styra/tickethub/ForbiddenExceptionWithReasonMapper.java
- server/java/src/main/java/com/styra/tickethub/TicketHub.java
This PR adds reason support to the Java server, leveraging the previous work I did to support it in the HTL client. It also updates the README with information about how reasons work in this demo.
> implement reason support for Java backend

- server/node/package-lock.json
- server/node/package.json
Referring to "main" was a silly idea. Package integrity checks block all usage of unstable references like those. Pinning a specific commit now.
> server/node: fix opa-typescript ref to ucast-prisma package

- client/react/src/UsersContext.js
- client/react/src/components/App.jsx
- client/react/src/components/Assignee.jsx
- client/react/src/components/Ticket.jsx
- client/react/src/components/Tickets.jsx
- policies/tickets.rego
- server/node/database/init.sql
- server/node/package-lock.json
- server/node/package.json
- server/node/prisma/schema.prisma
- server/node/src/api.js
- tests/api/conditions.hurl
- tests/e2e/tests/tickets.spec.ts
Admin users can see and change assignments:
---------------
Resolver users can now only see unresolved tickets **AND** all tickets assigned to them:
> database+node+react: add assignee, for livelier conditions

- policies/tickets.rego
`@styra/ucast-prisma` v0.0.4 handles empty `or` conditions better, so we can write policies that build up `or` conditions -- which may then also be empty, if, for example, a more privileged user makes the request.
Previously, we'd run into a prisma error because it doesn't like being fed and empty `OR: []`.
> policies/tickets.rego: make conditions.or more idiomatic

- policies/tickets.rego
- server/node/package-lock.json
- server/node/package.json
- tests/api/conditions.hurl
The conditions for resolver users have been changed: they can list tickets iff they are either assigned to them (status doesn't matter) OR unassigned+unresolved. So before, Ceasar would be able to see the unresolved tickets that had been assigned to Bob; now, they cannot.
----
needs https://github.com/StyraInc/opa-typescript/pull/343 ✔️
> policies: filter out assigned+unresolved tickets

- policies/tickets.rego
- server/node/src/api.js
- server/node/src/authz.js
With this change, **all** of our "list tickets" _where_ clauses are determined by the policy eval result, even the tenancy filter.
> policies+node: move tenant-check into WHERE conditions for "list"

- client/react/Makefile
- client/react/src/components/Ticket.jsx
- client/react/src/components/Tickets.jsx
- server/node/Makefile
- server/node/src/api.js
- tests/api/conditions.hurl
Had to make server/node return `"assignee": null` to differentiate, but that's probably OK.
> client/react: hide "assignee" dropdown when backend doesn't support it

- .github/workflows/pull-request.yaml
- policies/tickets_expanded.rego
- server/csharp/Dockerfile
- server/csharp/TicketHub/Authorization/QueryableExtensions.cs
- server/csharp/TicketHub/Authorization/UCASTNode.cs
- server/csharp/TicketHub/Controllers/TicketController.cs
- server/csharp/TicketHub/Database/Customer.cs
- server/csharp/TicketHub/Database/PostgresContext.cs
- server/csharp/TicketHub/Database/Tenant.cs
- server/csharp/TicketHub/Database/Ticket.cs
- server/csharp/TicketHub/Database/User.cs
- server/csharp/database/init.sql
This PR embodies the suite of changes required to integrate UCAST with LINQ queries. I've picked the C# server as the initial "landing zone" for these changes, since it's easier to pare back the layers here than in the ASP.NET Core SDK server.
Spin up the `csharp` server using:
docker compose build server-csharp --parallel && docker compose --profile csharp up
If all went well, you should be able to query the TicketHub server directly with `curl`, as shown below:
```bash
curl --header 'Content-Type: application/json' --header 'Authorization: Bearer acmecorp / ceasar' --cookie 'user=acmecorp / ceasar' 'http://localhost:4000/api/tickets'
```
<details>
<summary>Example Output</summary>
```json
{"tickets":[{"id":3,"description":"Latest android exhibit depression …
```
> server/csharp: Add initial stab at LINQ+UCAST support.

- .github/workflows/pull-request.yaml
- client/react/src/components/App.jsx
- client/react/src/components/Ticket.jsx
- client/react/src/components/Tickets.jsx
- tests/e2e/package-lock.json
- tests/e2e/package.json
- tests/e2e/tests/tickets.spec.ts
Turns out it's not been related to the ordering of tickets in the list view -- we had already taken precautions for that. It's been a timing issue. Adding a "wait for API request to finish" type of step in the relevant test, and it seems to be enough. After all, the behaviour of the C# backend and the react client was OK, it just failed the test.
Kept the sorting anyways, most recently updated tickets come first.
> ci: enable conditions PW tests for C#

- server/csharp/TicketHub/Authorization/QueryableExtensions.cs
- server/csharp/TicketHub/Authorization/UCASTNode.cs
- server/csharp/TicketHub/Controllers/TicketController.cs
- server/csharp/TicketHub/Database/Ticket.cs
This PR includes some basic dead-code cleanups, along with a new "default mapping" utility, which handles converting EF Core model classes into property mapping dictionaries, in a way that makes sense, based on our current UCAST conditions policies.
Example translations of class property names -> UCAST property names:
- `Example.Id` -> `"example.id"`
- `Example.LastUpdated` -> `"example.last_updated"`
- `Example.UserNavigation.Id` -> `"example.user.id"`
This makes creating property mappings *enormously* less of a hassle for LINQ/EF Core use cases.
The PR shows how to manually add/remove keys from the mapper, because the conditons policy expects `users.name`, instead of `tickets.user.name`, for example. Here's the list of default keys generated by the mapper function:
<details> …
> server/csharp: UCAST+LINQ refactors + default mapping logic

- .github/dependabot.yml
springboot doesn't use that dependency.
> dependabot: update jetty+jersey together, remove from springboot

- .github/workflows/pull-request.yaml
- policies/filters.rego
- server/node/src/api.js
- server/node/src/authz.js
This PR makes server/node no longer use the manual conditions construction approach, but use the (experimental!) /exp/compile API instead.
👉 [These are the filter rules.](https://github.com/StyraInc/styra-demo-tickethub/pull/524/files#diff-df04551bdddbe4af2cfc0c70263cea57135d995a37eb2ecab3f9368082531be5)
> server/node: use /exp/compile API with UCAST target

- policies/filters.rego
- server/csharp/TicketHub/Controllers/TicketController.cs
- server/csharp/TicketHub/TicketHub.csproj
This PR wraps up changes in the C# server to support using the combined data filters and column masks from the extended Compile API in Enterprise OPA.
Things that needed updating:
- Pulling in the upstream ucast-linq changes (`0.4.0` supports the nested dictionary lookups we need)
- Extracting both conditions and masks from the `/v1/compile/{path}` API call.
- Reworking the filtering policy to use the modern mask rule style
Next steps after this PR:
- Update the `OpaClient` APIs over in opa-csharp, to allow removing the custom `GetConditions` "shim" call here.
> server/csharp: Change to support nested-object masking style.

- .github/pull_request_template.md
This PR adds a basic template for future PRs. It's based on a PR format originally created by @msorens, which we've used on other projects with some success.
Below the line is a sample of what will show up in future PRs:
-----
> .github: Add default PR template

- server/csharp/TicketHub/Authorization/OpaAuthorizationAttribute.cs
- server/csharp/TicketHub/Controllers/TicketController.cs
- server/csharp/TicketHub/TicketHub.csproj
Recent breakging updates in the `Styra.Opa` package mean that we have to manually refactor some of our function/method calls over here in the server implementation.
- Do the build and unit test jobs run without error now?
> server/csharp: Breaking updates for the 1.5.x Styra.Opa package.
